from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QTimer, Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 300)
        self.central_widget = QtWidgets.QWidget(parent=MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout = QtWidgets.QVBoxLayout()
        self.layout.setObjectName("layout")
        self.image_label = QtWidgets.QLabel(parent=self.central_widget)
        self.image_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.image_label.setMinimumSize(400, 400)
        self.image_label.setScaledContents(True)
        self.image_label.setObjectName("image_label")
        self.layout.addWidget(self.image_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prev_button = QtWidgets.QPushButton(parent=self.central_widget)
        self.prev_button.setMinimumSize(QtCore.QSize(100, 100))
        self.prev_button.setObjectName("prev_button")
        self.horizontalLayout.addWidget(self.prev_button)
        self.first_button = QtWidgets.QPushButton(parent=self.central_widget)
        self.first_button.setMinimumSize(QtCore.QSize(50, 50))
        self.first_button.setObjectName("first_button")
        self.horizontalLayout.addWidget(self.first_button)
        self.slide_show_button = QtWidgets.QPushButton(parent=self.central_widget)
        self.slide_show_button.setMinimumSize(QtCore.QSize(50, 50))
        self.slide_show_button.setObjectName("slide_show_button")
        self.horizontalLayout.addWidget(self.slide_show_button)
        self.delete_button = QtWidgets.QPushButton(parent=self.central_widget)
        self.delete_button.setMinimumSize(QtCore.QSize(50, 50))
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        self.rotate_button = QtWidgets.QPushButton(parent=self.central_widget)
        self.rotate_button.setMinimumSize(QtCore.QSize(50, 50))
        self.rotate_button.setObjectName("rotate_button")
        self.horizontalLayout.addWidget(self.rotate_button)
        self.last_button = QtWidgets.QPushButton(parent=self.central_widget)
        self.last_button.setMinimumSize(QtCore.QSize(50, 50))
        self.last_button.setObjectName("last_button")
        self.horizontalLayout.addWidget(self.last_button)
        self.next_button = QtWidgets.QPushButton(parent=self.central_widget)
        self.next_button.setMinimumSize(QtCore.QSize(100, 100))
        self.next_button.setObjectName("next_button")
        self.horizontalLayout.addWidget(self.next_button)
        self.layout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.layout)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.prev_button.setText(_translate("MainWindow", "Previous"))
        self.first_button.setText(_translate("MainWindow", "First"))
        self.slide_show_button.setText(_translate("MainWindow", "Slide Show"))
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        self.rotate_button.setText(_translate("MainWindow", "Rotate"))
        self.last_button.setText(_translate("MainWindow", "Last"))
        self.next_button.setText(_translate("MainWindow", "Next"))
